#pragma once
#include"Gate.h"
#include"AND_Gate.h"
#include"OR_Gate.h"
#include"InputGate.h"
#include"NOR_Gate.h"
#include"NAND_Gate.h"
#include"XOR_Gate.h"
#include"XNOR_Gate.h"
#include"NOT_Gate.h"